import type { AuditInput, AuditResult, CategoryKey, Opportunity, Priority, WebsiteSignals } from "./types.ts";

const labels: Record<CategoryKey, string> = { website: "Website", localSeo: "Local SEO", reputation: "Reputation", leadGeneration: "Lead Generation", offer: "Offer", content: "Content" };

export function buildRecommendations(input: AuditInput, signals: WebsiteSignals, categories: AuditResult["categories"]): Opportunity[] {
  return (Object.entries(categories) as [CategoryKey, number][]).sort(([, first], [, second]) => first - second).slice(0, 3).map(([category, score]) => {
    const detail = details[category](input, signals);
    return { category: labels[category], score, priority: priorityFor(score), ...detail };
  });
}

export function priorityFor(score: number): Priority { return score < 40 ? "CRITICAL" : score < 60 ? "HIGH" : score < 75 ? "MEDIUM" : score < 90 ? "GOOD" : "EXCELLENT"; }

const details: Record<CategoryKey, (input: AuditInput, signals: WebsiteSignals) => Pick<Opportunity, "title" | "explanation" | "recommendations">> = {
  website: (_, signals) => ({ title: "Give the website a stronger foundation", explanation: signals.fetched ? "Core on-page signals are missing, making it harder for visitors and search engines to understand the business." : "The website could not be fully inspected, so its technical foundation needs a manual check.", recommendations: [!signals.title ? "Add a specific page title." : "Refine the page title around the primary service.", !signals.metaDescription ? "Write a useful meta description for the main page." : "Make the meta description emphasize the customer outcome.", !signals.viewport ? "Add a mobile viewport declaration." : "Review the mobile layout on a real device."] }),
  localSeo: (input, signals) => ({ title: "Make the local market unmistakable", explanation: `Visitors searching for ${input.industry} in ${input.city} should immediately see that this business serves them.`, recommendations: [!signals.hasLocationSignal ? `Mention ${input.city} and service areas in visible page copy.` : "Expand service-area proof with dedicated local pages.", !signals.hasAddress ? "Add consistent local business details or service-area information." : "Keep the address and local business details consistent.", "Connect each priority service to the markets it serves."] }),
  reputation: (_, signals) => ({ title: "Put customer proof to work", explanation: "The site has limited detectable proof that reduces uncertainty before a visitor reaches out.", recommendations: [!signals.hasTestimonials && !signals.hasReviews ? "Add specific customer testimonials or review excerpts." : "Move the strongest review proof near conversion points.", !signals.hasGuarantee ? "Explain a relevant guarantee or customer promise." : "Make the guarantee prominent on service pages.", !signals.hasCertification && !signals.hasTrustBadge ? "Show relevant licenses, certifications, or associations." : "Link trust badges to verifiable details."] }),
  leadGeneration: (_, signals) => ({ title: "Make the next step obvious", explanation: "There are not enough clearly detectable ways for a ready-to-buy visitor to contact or book the business.", recommendations: [!signals.hasStrongCTA ? "Add a clear quote, estimate, call, or booking CTA." : "Repeat the strongest CTA near high-intent content.", !signals.hasPhone ? "Add a tap-to-call phone number." : "Make the phone number prominent on mobile.", !signals.hasContactForm && !signals.hasBookingLink ? "Add a short contact, quote, or booking path." : "Test the form or booking path from a new customer's perspective."] }),
  offer: (input, signals) => ({ title: "Clarify the service outcome", explanation: `The ${input.industry} offer should explain the result, fit, and next step in seconds.`, recommendations: [!signals.hasServiceContent ? "Describe the core services in customer language." : "Lead with the highest-value service and outcome.", !signals.hasStrongCTA ? "Pair the offer with a specific estimate or booking CTA." : "Tie the CTA to a concrete customer outcome.", !signals.hasGuarantee ? "Add a credible promise that reduces purchase risk." : "Make the customer promise easier to find."] }),
  content: (_, signals) => ({ title: "Answer the questions before the call", explanation: "The site needs more useful, structured content to build confidence during the research phase.", recommendations: [signals.h2.length < 2 ? "Add clear sections answering common customer questions." : "Turn the strongest sections into focused service content.", !signals.hasPortfolio ? "Show completed projects, case studies, or examples of work." : "Add outcomes and context to project examples.", !signals.hasServiceContent ? "Create a dedicated page for the primary service." : "Publish one local service answer each week."] }),
};

export function buildLegacyFields(top: Opportunity[], categories: AuditResult["categories"], signals: WebsiteSignals, input: AuditInput) {
  const strengths = [signals.https ? "Secure website connection" : "A clear technical starting point", signals.hasStrongCTA ? "A visible conversion path" : "Room to improve the conversion path", input.city ? `A defined local market in ${input.city}` : "A focused local-market opportunity"];
  const opportunities = top.map((item) => `${item.title}|${item.explanation}`);
  const first = top[0];
  return { strengths, opportunities, priority: { category: first.category, title: first.title, description: first.explanation, impact: first.priority === "CRITICAL" || first.priority === "HIGH" ? "High" as const : "Medium" as const }, actions: top.flatMap((item) => item.recommendations.slice(0, 2).map((recommendation, index) => ({ title: recommendation, description: item.explanation, priority: index === 0 ? "High" as const : "Medium" as const }))).slice(0, 5) };
}
